services:
  sftp-test:
    image: atmoz/sftp
    container_name: sftp-test
    ports:
      - "2223:22"
    command: david:test123:1000:1000:upload
    volumes:
        - ./sftp-data:/home/david/upload
    restart: unless-stopped