spring:
  application:
    version: 0.1.0
    name: backend

  datasource:
    driver-class-name: org.postgresql.Driver
    password: "${POSTGRES_PASSWORD}"
    username: "${POSTGRES_USER}"
    url: "jdbc:postgresql://localhost:5432/${POSTGRES_DB}"

  liquibase:
    enabled: true
    password: "${POSTGRES_PASSWORD}"
    user: "${POSTGRES_USER}"
    url: "jdbc:postgresql://localhost:5432/${POSTGRES_DB}"
    change-log: "classpath:/db/db.changelog-master.xml"

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: 6379

springdotenv:
  enabled: true
  filename: .env

pbm:
  master-key: ${PBM_MASTER_KEY}
  jwt:
    secret: "${PBM_JWT_SECRET}"